spring.application.name=zeePlus-server

server.port=8084

spring.datasource.url=jdbc:postgresql://localhost:5433/zeePlus
spring.datasource.username=zeePlus_db
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate
