/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PharmacistVerifyOtpRouteImport } from './routes/pharmacist.verify-otp'
import { Route as PharmacistInventoryRouteImport } from './routes/pharmacist.inventory'
import { Route as PharmacistDistributionRouteImport } from './routes/pharmacist.distribution'
import { Route as PharmacistDispenseRouteImport } from './routes/pharmacist.dispense'
import { Route as PharmacistDashboardRouteImport } from './routes/pharmacist.dashboard'
import { Route as PatientMyAppointmentsRouteImport } from './routes/patient.my-appointments'
import { Route as PatientGenerateOtpRouteImport } from './routes/patient.generate-otp'
import { Route as PatientDashboardRouteImport } from './routes/patient.dashboard'
import { Route as PatientConsultRouteImport } from './routes/patient.consult'
import { Route as PatientBookAppointmentRouteImport } from './routes/patient.book-appointment'
import { Route as DoctorMedicationRouteImport } from './routes/doctor.medication'
import { Route as DoctorDashboardRouteImport } from './routes/doctor.dashboard'
import { Route as DoctorConsultationRouteImport } from './routes/doctor.consultation'
import { Route as AdminVerifyAppointmentRouteImport } from './routes/admin.verify-appointment'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminManageAppointmentsRouteImport } from './routes/admin.manage-appointments'
import { Route as AdminFraudAlertsRouteImport } from './routes/admin.fraud-alerts'
import { Route as AdminEligibilityRouteImport } from './routes/admin.eligibility'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminClaimsRouteImport } from './routes/admin.claims'
import { Route as AdminAuthRouteImport } from './routes/admin.auth'
import { Route as AdminAssignDoctorRouteImport } from './routes/admin.assign-doctor'
import { Route as DoctorPrescriptionUploadRouteImport } from './routes/doctor.prescription.upload'
import { Route as DoctorPrescriptionUpgradeRouteImport } from './routes/doctor.prescription.upgrade'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmacistVerifyOtpRoute = PharmacistVerifyOtpRouteImport.update({
  id: '/pharmacist/verify-otp',
  path: '/pharmacist/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmacistInventoryRoute = PharmacistInventoryRouteImport.update({
  id: '/pharmacist/inventory',
  path: '/pharmacist/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmacistDistributionRoute = PharmacistDistributionRouteImport.update({
  id: '/pharmacist/distribution',
  path: '/pharmacist/distribution',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmacistDispenseRoute = PharmacistDispenseRouteImport.update({
  id: '/pharmacist/dispense',
  path: '/pharmacist/dispense',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmacistDashboardRoute = PharmacistDashboardRouteImport.update({
  id: '/pharmacist/dashboard',
  path: '/pharmacist/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientMyAppointmentsRoute = PatientMyAppointmentsRouteImport.update({
  id: '/patient/my-appointments',
  path: '/patient/my-appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientGenerateOtpRoute = PatientGenerateOtpRouteImport.update({
  id: '/patient/generate-otp',
  path: '/patient/generate-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientDashboardRoute = PatientDashboardRouteImport.update({
  id: '/patient/dashboard',
  path: '/patient/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientConsultRoute = PatientConsultRouteImport.update({
  id: '/patient/consult',
  path: '/patient/consult',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientBookAppointmentRoute = PatientBookAppointmentRouteImport.update({
  id: '/patient/book-appointment',
  path: '/patient/book-appointment',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorMedicationRoute = DoctorMedicationRouteImport.update({
  id: '/doctor/medication',
  path: '/doctor/medication',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorDashboardRoute = DoctorDashboardRouteImport.update({
  id: '/doctor/dashboard',
  path: '/doctor/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorConsultationRoute = DoctorConsultationRouteImport.update({
  id: '/doctor/consultation',
  path: '/doctor/consultation',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVerifyAppointmentRoute = AdminVerifyAppointmentRouteImport.update({
  id: '/admin/verify-appointment',
  path: '/admin/verify-appointment',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminManageAppointmentsRoute = AdminManageAppointmentsRouteImport.update({
  id: '/admin/manage-appointments',
  path: '/admin/manage-appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFraudAlertsRoute = AdminFraudAlertsRouteImport.update({
  id: '/admin/fraud-alerts',
  path: '/admin/fraud-alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEligibilityRoute = AdminEligibilityRouteImport.update({
  id: '/admin/eligibility',
  path: '/admin/eligibility',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminClaimsRoute = AdminClaimsRouteImport.update({
  id: '/admin/claims',
  path: '/admin/claims',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthRoute = AdminAuthRouteImport.update({
  id: '/admin/auth',
  path: '/admin/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAssignDoctorRoute = AdminAssignDoctorRouteImport.update({
  id: '/admin/assign-doctor',
  path: '/admin/assign-doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorPrescriptionUploadRoute =
  DoctorPrescriptionUploadRouteImport.update({
    id: '/doctor/prescription/upload',
    path: '/doctor/prescription/upload',
    getParentRoute: () => rootRouteImport,
  } as any)
const DoctorPrescriptionUpgradeRoute =
  DoctorPrescriptionUpgradeRouteImport.update({
    id: '/doctor/prescription/upgrade',
    path: '/doctor/prescription/upgrade',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/sign-in': typeof SignInRoute
  '/admin/assign-doctor': typeof AdminAssignDoctorRoute
  '/admin/auth': typeof AdminAuthRoute
  '/admin/claims': typeof AdminClaimsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/eligibility': typeof AdminEligibilityRoute
  '/admin/fraud-alerts': typeof AdminFraudAlertsRoute
  '/admin/manage-appointments': typeof AdminManageAppointmentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verify-appointment': typeof AdminVerifyAppointmentRoute
  '/doctor/consultation': typeof DoctorConsultationRoute
  '/doctor/dashboard': typeof DoctorDashboardRoute
  '/doctor/medication': typeof DoctorMedicationRoute
  '/patient/book-appointment': typeof PatientBookAppointmentRoute
  '/patient/consult': typeof PatientConsultRoute
  '/patient/dashboard': typeof PatientDashboardRoute
  '/patient/generate-otp': typeof PatientGenerateOtpRoute
  '/patient/my-appointments': typeof PatientMyAppointmentsRoute
  '/pharmacist/dashboard': typeof PharmacistDashboardRoute
  '/pharmacist/dispense': typeof PharmacistDispenseRoute
  '/pharmacist/distribution': typeof PharmacistDistributionRoute
  '/pharmacist/inventory': typeof PharmacistInventoryRoute
  '/pharmacist/verify-otp': typeof PharmacistVerifyOtpRoute
  '/doctor/prescription/upgrade': typeof DoctorPrescriptionUpgradeRoute
  '/doctor/prescription/upload': typeof DoctorPrescriptionUploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/sign-in': typeof SignInRoute
  '/admin/assign-doctor': typeof AdminAssignDoctorRoute
  '/admin/auth': typeof AdminAuthRoute
  '/admin/claims': typeof AdminClaimsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/eligibility': typeof AdminEligibilityRoute
  '/admin/fraud-alerts': typeof AdminFraudAlertsRoute
  '/admin/manage-appointments': typeof AdminManageAppointmentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verify-appointment': typeof AdminVerifyAppointmentRoute
  '/doctor/consultation': typeof DoctorConsultationRoute
  '/doctor/dashboard': typeof DoctorDashboardRoute
  '/doctor/medication': typeof DoctorMedicationRoute
  '/patient/book-appointment': typeof PatientBookAppointmentRoute
  '/patient/consult': typeof PatientConsultRoute
  '/patient/dashboard': typeof PatientDashboardRoute
  '/patient/generate-otp': typeof PatientGenerateOtpRoute
  '/patient/my-appointments': typeof PatientMyAppointmentsRoute
  '/pharmacist/dashboard': typeof PharmacistDashboardRoute
  '/pharmacist/dispense': typeof PharmacistDispenseRoute
  '/pharmacist/distribution': typeof PharmacistDistributionRoute
  '/pharmacist/inventory': typeof PharmacistInventoryRoute
  '/pharmacist/verify-otp': typeof PharmacistVerifyOtpRoute
  '/doctor/prescription/upgrade': typeof DoctorPrescriptionUpgradeRoute
  '/doctor/prescription/upload': typeof DoctorPrescriptionUploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/sign-in': typeof SignInRoute
  '/admin/assign-doctor': typeof AdminAssignDoctorRoute
  '/admin/auth': typeof AdminAuthRoute
  '/admin/claims': typeof AdminClaimsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/eligibility': typeof AdminEligibilityRoute
  '/admin/fraud-alerts': typeof AdminFraudAlertsRoute
  '/admin/manage-appointments': typeof AdminManageAppointmentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verify-appointment': typeof AdminVerifyAppointmentRoute
  '/doctor/consultation': typeof DoctorConsultationRoute
  '/doctor/dashboard': typeof DoctorDashboardRoute
  '/doctor/medication': typeof DoctorMedicationRoute
  '/patient/book-appointment': typeof PatientBookAppointmentRoute
  '/patient/consult': typeof PatientConsultRoute
  '/patient/dashboard': typeof PatientDashboardRoute
  '/patient/generate-otp': typeof PatientGenerateOtpRoute
  '/patient/my-appointments': typeof PatientMyAppointmentsRoute
  '/pharmacist/dashboard': typeof PharmacistDashboardRoute
  '/pharmacist/dispense': typeof PharmacistDispenseRoute
  '/pharmacist/distribution': typeof PharmacistDistributionRoute
  '/pharmacist/inventory': typeof PharmacistInventoryRoute
  '/pharmacist/verify-otp': typeof PharmacistVerifyOtpRoute
  '/doctor/prescription/upgrade': typeof DoctorPrescriptionUpgradeRoute
  '/doctor/prescription/upload': typeof DoctorPrescriptionUploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/register'
    | '/sign-in'
    | '/admin/assign-doctor'
    | '/admin/auth'
    | '/admin/claims'
    | '/admin/dashboard'
    | '/admin/eligibility'
    | '/admin/fraud-alerts'
    | '/admin/manage-appointments'
    | '/admin/reports'
    | '/admin/users'
    | '/admin/verify-appointment'
    | '/doctor/consultation'
    | '/doctor/dashboard'
    | '/doctor/medication'
    | '/patient/book-appointment'
    | '/patient/consult'
    | '/patient/dashboard'
    | '/patient/generate-otp'
    | '/patient/my-appointments'
    | '/pharmacist/dashboard'
    | '/pharmacist/dispense'
    | '/pharmacist/distribution'
    | '/pharmacist/inventory'
    | '/pharmacist/verify-otp'
    | '/doctor/prescription/upgrade'
    | '/doctor/prescription/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/register'
    | '/sign-in'
    | '/admin/assign-doctor'
    | '/admin/auth'
    | '/admin/claims'
    | '/admin/dashboard'
    | '/admin/eligibility'
    | '/admin/fraud-alerts'
    | '/admin/manage-appointments'
    | '/admin/reports'
    | '/admin/users'
    | '/admin/verify-appointment'
    | '/doctor/consultation'
    | '/doctor/dashboard'
    | '/doctor/medication'
    | '/patient/book-appointment'
    | '/patient/consult'
    | '/patient/dashboard'
    | '/patient/generate-otp'
    | '/patient/my-appointments'
    | '/pharmacist/dashboard'
    | '/pharmacist/dispense'
    | '/pharmacist/distribution'
    | '/pharmacist/inventory'
    | '/pharmacist/verify-otp'
    | '/doctor/prescription/upgrade'
    | '/doctor/prescription/upload'
  id:
    | '__root__'
    | '/'
    | '/register'
    | '/sign-in'
    | '/admin/assign-doctor'
    | '/admin/auth'
    | '/admin/claims'
    | '/admin/dashboard'
    | '/admin/eligibility'
    | '/admin/fraud-alerts'
    | '/admin/manage-appointments'
    | '/admin/reports'
    | '/admin/users'
    | '/admin/verify-appointment'
    | '/doctor/consultation'
    | '/doctor/dashboard'
    | '/doctor/medication'
    | '/patient/book-appointment'
    | '/patient/consult'
    | '/patient/dashboard'
    | '/patient/generate-otp'
    | '/patient/my-appointments'
    | '/pharmacist/dashboard'
    | '/pharmacist/dispense'
    | '/pharmacist/distribution'
    | '/pharmacist/inventory'
    | '/pharmacist/verify-otp'
    | '/doctor/prescription/upgrade'
    | '/doctor/prescription/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RegisterRoute: typeof RegisterRoute
  SignInRoute: typeof SignInRoute
  AdminAssignDoctorRoute: typeof AdminAssignDoctorRoute
  AdminAuthRoute: typeof AdminAuthRoute
  AdminClaimsRoute: typeof AdminClaimsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminEligibilityRoute: typeof AdminEligibilityRoute
  AdminFraudAlertsRoute: typeof AdminFraudAlertsRoute
  AdminManageAppointmentsRoute: typeof AdminManageAppointmentsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVerifyAppointmentRoute: typeof AdminVerifyAppointmentRoute
  DoctorConsultationRoute: typeof DoctorConsultationRoute
  DoctorDashboardRoute: typeof DoctorDashboardRoute
  DoctorMedicationRoute: typeof DoctorMedicationRoute
  PatientBookAppointmentRoute: typeof PatientBookAppointmentRoute
  PatientConsultRoute: typeof PatientConsultRoute
  PatientDashboardRoute: typeof PatientDashboardRoute
  PatientGenerateOtpRoute: typeof PatientGenerateOtpRoute
  PatientMyAppointmentsRoute: typeof PatientMyAppointmentsRoute
  PharmacistDashboardRoute: typeof PharmacistDashboardRoute
  PharmacistDispenseRoute: typeof PharmacistDispenseRoute
  PharmacistDistributionRoute: typeof PharmacistDistributionRoute
  PharmacistInventoryRoute: typeof PharmacistInventoryRoute
  PharmacistVerifyOtpRoute: typeof PharmacistVerifyOtpRoute
  DoctorPrescriptionUpgradeRoute: typeof DoctorPrescriptionUpgradeRoute
  DoctorPrescriptionUploadRoute: typeof DoctorPrescriptionUploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacist/verify-otp': {
      id: '/pharmacist/verify-otp'
      path: '/pharmacist/verify-otp'
      fullPath: '/pharmacist/verify-otp'
      preLoaderRoute: typeof PharmacistVerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacist/inventory': {
      id: '/pharmacist/inventory'
      path: '/pharmacist/inventory'
      fullPath: '/pharmacist/inventory'
      preLoaderRoute: typeof PharmacistInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacist/distribution': {
      id: '/pharmacist/distribution'
      path: '/pharmacist/distribution'
      fullPath: '/pharmacist/distribution'
      preLoaderRoute: typeof PharmacistDistributionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacist/dispense': {
      id: '/pharmacist/dispense'
      path: '/pharmacist/dispense'
      fullPath: '/pharmacist/dispense'
      preLoaderRoute: typeof PharmacistDispenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacist/dashboard': {
      id: '/pharmacist/dashboard'
      path: '/pharmacist/dashboard'
      fullPath: '/pharmacist/dashboard'
      preLoaderRoute: typeof PharmacistDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/my-appointments': {
      id: '/patient/my-appointments'
      path: '/patient/my-appointments'
      fullPath: '/patient/my-appointments'
      preLoaderRoute: typeof PatientMyAppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/generate-otp': {
      id: '/patient/generate-otp'
      path: '/patient/generate-otp'
      fullPath: '/patient/generate-otp'
      preLoaderRoute: typeof PatientGenerateOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/dashboard': {
      id: '/patient/dashboard'
      path: '/patient/dashboard'
      fullPath: '/patient/dashboard'
      preLoaderRoute: typeof PatientDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/consult': {
      id: '/patient/consult'
      path: '/patient/consult'
      fullPath: '/patient/consult'
      preLoaderRoute: typeof PatientConsultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/book-appointment': {
      id: '/patient/book-appointment'
      path: '/patient/book-appointment'
      fullPath: '/patient/book-appointment'
      preLoaderRoute: typeof PatientBookAppointmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/medication': {
      id: '/doctor/medication'
      path: '/doctor/medication'
      fullPath: '/doctor/medication'
      preLoaderRoute: typeof DoctorMedicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/dashboard': {
      id: '/doctor/dashboard'
      path: '/doctor/dashboard'
      fullPath: '/doctor/dashboard'
      preLoaderRoute: typeof DoctorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/consultation': {
      id: '/doctor/consultation'
      path: '/doctor/consultation'
      fullPath: '/doctor/consultation'
      preLoaderRoute: typeof DoctorConsultationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/verify-appointment': {
      id: '/admin/verify-appointment'
      path: '/admin/verify-appointment'
      fullPath: '/admin/verify-appointment'
      preLoaderRoute: typeof AdminVerifyAppointmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/manage-appointments': {
      id: '/admin/manage-appointments'
      path: '/admin/manage-appointments'
      fullPath: '/admin/manage-appointments'
      preLoaderRoute: typeof AdminManageAppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/fraud-alerts': {
      id: '/admin/fraud-alerts'
      path: '/admin/fraud-alerts'
      fullPath: '/admin/fraud-alerts'
      preLoaderRoute: typeof AdminFraudAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/eligibility': {
      id: '/admin/eligibility'
      path: '/admin/eligibility'
      fullPath: '/admin/eligibility'
      preLoaderRoute: typeof AdminEligibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/claims': {
      id: '/admin/claims'
      path: '/admin/claims'
      fullPath: '/admin/claims'
      preLoaderRoute: typeof AdminClaimsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/auth': {
      id: '/admin/auth'
      path: '/admin/auth'
      fullPath: '/admin/auth'
      preLoaderRoute: typeof AdminAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/assign-doctor': {
      id: '/admin/assign-doctor'
      path: '/admin/assign-doctor'
      fullPath: '/admin/assign-doctor'
      preLoaderRoute: typeof AdminAssignDoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/prescription/upload': {
      id: '/doctor/prescription/upload'
      path: '/doctor/prescription/upload'
      fullPath: '/doctor/prescription/upload'
      preLoaderRoute: typeof DoctorPrescriptionUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/prescription/upgrade': {
      id: '/doctor/prescription/upgrade'
      path: '/doctor/prescription/upgrade'
      fullPath: '/doctor/prescription/upgrade'
      preLoaderRoute: typeof DoctorPrescriptionUpgradeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RegisterRoute: RegisterRoute,
  SignInRoute: SignInRoute,
  AdminAssignDoctorRoute: AdminAssignDoctorRoute,
  AdminAuthRoute: AdminAuthRoute,
  AdminClaimsRoute: AdminClaimsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminEligibilityRoute: AdminEligibilityRoute,
  AdminFraudAlertsRoute: AdminFraudAlertsRoute,
  AdminManageAppointmentsRoute: AdminManageAppointmentsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVerifyAppointmentRoute: AdminVerifyAppointmentRoute,
  DoctorConsultationRoute: DoctorConsultationRoute,
  DoctorDashboardRoute: DoctorDashboardRoute,
  DoctorMedicationRoute: DoctorMedicationRoute,
  PatientBookAppointmentRoute: PatientBookAppointmentRoute,
  PatientConsultRoute: PatientConsultRoute,
  PatientDashboardRoute: PatientDashboardRoute,
  PatientGenerateOtpRoute: PatientGenerateOtpRoute,
  PatientMyAppointmentsRoute: PatientMyAppointmentsRoute,
  PharmacistDashboardRoute: PharmacistDashboardRoute,
  PharmacistDispenseRoute: PharmacistDispenseRoute,
  PharmacistDistributionRoute: PharmacistDistributionRoute,
  PharmacistInventoryRoute: PharmacistInventoryRoute,
  PharmacistVerifyOtpRoute: PharmacistVerifyOtpRoute,
  DoctorPrescriptionUpgradeRoute: DoctorPrescriptionUpgradeRoute,
  DoctorPrescriptionUploadRoute: DoctorPrescriptionUploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
